In [33]:
import pandas as pd

In [113]:

path = r"C:\Users\angel\Downloads\archive (6)\steamspy_data.csv"
df = pd.read_csv(path)
pd.set_option("display.max_columns", None)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29235 entries, 0 to 29234
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            29235 non-null  int64
 1   name             29230 non-null  object
 2   developer        29038 non-null  object
 3   publisher        28955 non-null  object
 4   score_rank       58 non-null     float64
 5   positive         29235 non-null  int64
 6   negative         29235 non-null  int64
 7   userscore        29235 non-null  int64
 8   owners           29235 non-null  object
 9   average_forever  29235 non-null  int64
 10  average_2weeks   29235 non-null  int64
 11  median_forever   29235 non-null  int64
 12  median_2weeks    29235 non-null  int64
 13  price            29206 non-null  float64
 14  initialprice     29213 non-null  float64
 15  discount         29213 non-null  float64
 16  languages        29141 non-null  object
 17  genre            29083 non-null  object
 18  ccu              29235 non-null  int64
 19  tags             29235 non-null  object
dtypes: float64(4), int64(9), object(7)
memory usage: 4.5+ MB

In [114]:
# drop uneccesary columns
df.drop(columns=['score_rank', 'initialprice', 'discount', 'positive', 'negative', 'ccu', 'owners', 'tags'], inplace=True)
df.head()

,appid,name,developer,publisher,userscore,average_forever,average_2weeks,median_forever,median_2weeks,price,languages,genre
0,10,Counter-Strike,Valve,Valve,0,17612,709,317,26,999.0,"English, French, German, Italian, Spanish - Sp...",Action
1,20,Team Fortress Classic,Valve,Valve,0,277,15,62,15,499.0,"English, French, German, Italian, Spanish - Sp...",Action
2,30,Day of Defeat,Valve,Valve,0,187,0,34,0,499.0,"English, French, German, Italian, Spanish - Spain",Action
3,40,Deathmatch Classic,Valve,Valve,0,258,0,184,0,499.0,"English, French, German, Italian, Spanish - Sp...",Action
4,50,Half-Life: Opposing Force,Gearbox Software,Valve,0,624,0,415,0,499.0,"English, French, German, Korean",Action

In [60]:
df.describe()

,appid,userscore,average_forever,average_2weeks,median_forever,median_2weeks,price
count,2.923500e+04,29235.000000,29235.000000,29235.000000,29235.000000,29235.000000,29206.000000
mean,5.937432e+05,0.148863,148.133846,7.162579,145.004652,7.732581,777.811374
std,2.528262e+05,3.439954,1913.429438,113.653011,2389.469023,124.511022,1135.277801
min,1.000000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.979200e+05,0.000000,0.000000,0.000000,0.000000,0.000000,199.000000
50%,5.982400e+05,0.000000,0.000000,0.000000,0.000000,0.000000,499.000000
75%,7.973700e+05,0.000000,0.000000,0.000000,0.000000,0.000000,999.000000
max,1.069460e+06,100.000000,190625.000000,9003.000000,190625.000000,9003.000000,59599.000000

In [126]:
#change column names to make more sense 
df.rename(columns={'average_forever': 'average_play_forever', 'average_2weeks': 'average_play_2weeks', 'median_forever': 'median_play_forever', 'median_2weeks':'median_play_2weeks'}, inplace=True)
#adjust price column from cents to dollars
df['price'] = df['price']/100

In [127]:
#counts for most common developers, publishers, and genres 
print(df['developer'].value_counts())
print('\n')
print(df['publisher'].value_counts())
print('\n')
print(df['genre'].value_counts())

Choice of Games                 95
KOEI TECMO GAMES CO., LTD.      72
Ripknot Systems                 62
Laush Dmitriy Sergeevich        53
Telltale Games                  52
                                ..
Tri-Coastal Games                1
Enigmatic                        1
重庆焱玩网络科技有限公司                     1
Animation Arts Creative GmbH     1
Adept Studios GD                 1
Name: developer, Length: 18209, dtype: int64


Big Fish Games      231
Strategy First      139
Ubisoft             120
Square Enix         108
THQ Nordic          106
                   ...
Hippy Lizard          1
PNxDesigns            1
White Door Games      1
ICA GAMES             1
SHEN JIAWEI           1
Name: publisher, Length: 15198, dtype: int64


Action, Indie                                                          1971
Casual, Indie                                                          1567
Action, Adventure, Indie                                               1311
Adventure, Indie                                                       1229
Action, Casual, Indie                                                  1061
                                                                       ...
Sexual Content, Simulation                                                1
Free to Play, RPG, Simulation                                             1
Action, Adventure, Indie, Massively Multiplayer, Racing, Simulation       1
Violent, Action, Casual, Free to Play, Indie                              1
Casual, Free to Play, Massively Multiplayer, RPG, Early Access            1
Name: genre, Length: 1624, dtype: int64

In [128]:
#find nulls in data
df.isnull().sum()

appid                     0
name                      5
developer               197
publisher               280
userscore                 0
average_play_forever      0
average_play_2weeks       0
median_play_forever       0
median_play_2weeks        0
price                    29
languages                94
genre                   152
dtype: int64

In [129]:
#clean out nulls
cleaned_df= df.dropna()
cleaned_df.isnull().sum()

appid                   0
name                    0
developer               0
publisher               0
userscore               0
average_play_forever    0
average_play_2weeks     0
median_play_forever     0
median_play_2weeks      0
price                   0
languages               0
genre                   0
dtype: int64

In [131]:
#find games with highest total average play time 
highest_playtime_alltime_df = cleaned_df.sort_values(by='average_play_forever', ascending = False)
highest_playtime_alltime_df.head()

,appid,name,developer,publisher,userscore,average_play_forever,average_play_2weeks,median_play_forever,median_play_2weeks,price,languages,genre
10033,474030,The Abbey of Crime Extensum,"Manuel Pazos, Daniel Celemín","Manuel Pazos, Daniel Celemín",0,190625,7,190625,7,0.0000,"English, Spanish - Spain, Italian, French","Adventure, Free to Play"
1706,219340,The Banner Saga: Factions,Stoic,Versus Evil,0,95245,8,190489,8,0.0000,English,"Free to Play, Indie, RPG, Strategy"
6605,380140,The Secret of Tremendous Corporation,"Sebastian Krzyszkowiak, Konrad Burandt, Paweł ...",dosowisko.net,0,95242,7,190445,7,0.0000,English,"Adventure, Casual, Free to Play, Indie"
9787,465520,PRICE,YETU GAME,YETU GAME,0,63481,7,63490,7,0.0000,"English, Simplified Chinese, Japanese","Adventure, Casual, Indie"
4375,324510,Boundless,Wonderstruck,Square Enix,0,55204,2151,55204,2151,0.3999,"English, French, Italian, German, Spanish - Spain","Action, Adventure, Indie, Massively Multiplaye..."

In [132]:
# find highest average played game by playtime over 2 weeks
highest_playtime_2weeks_df= cleaned_df.sort_values(by='average_play_2weeks', ascending= False)
highest_playtime_2weeks_df.head()

,appid,name,developer,publisher,userscore,average_play_forever,average_play_2weeks,median_play_forever,median_play_2weeks,price,languages,genre
289,9880,Champions Online,Cryptic Studios,Perfect World Entertainment,0,12952,9003,724,9003,0.0000,English,"Free to Play, Massively Multiplayer, RPG"
18541,707010,Will To Live Online,AlphaSoft LLC,AlphaSoft LLC,0,2951,8098,5759,8098,0.1199,"English, Russian, German, Simplified Chinese","Action, Indie, Massively Multiplayer, RPG, Ear..."
4418,326160,Shroud of the Avatar: Forsaken Virtues,Portalarium,Portalarium,0,54618,4538,54618,4538,0.0000,"English, Russian","Free to Play, Massively Multiplayer, RPG"
8782,439700,Z1 Battle Royale: Test Server,NantG,Daybreak Game Company,0,569,4389,61,4389,0.0000,English,Massively Multiplayer
15676,629520,Soundpad,Leppsoft,Leppsoft,0,11122,3425,17405,3425,0.0499,"English, German, French, Korean, Portuguese - ...","Audio Production, Utilities"